export interface ProphetConfig {
  en: string;
  label: string;
  color: string;
  bg: string;
  image: string;
  icon: string;
  bio: string;
  tags: string[];
}

export const PROPHETS: Record<string, ProphetConfig> = {
  '比格斯': {
    en: 'Brandon Biggs',
    label: '比格斯',
    color: '#f59e0b',
    bg: 'rgba(245,158,11,.12)',
    image: '/biggs-prophet.png',
    icon: '🎙',
    bio: '美國末世預言家，Last Days 頻道創辦人，精準預言川普安危、日本火山及多次全球大事',
    tags: ['基督教預言', '末世', '靈異異象'],
  },
  '帕克': {
    en: 'Craig Hamilton Parker',
    label: '帕克',
    color: '#3b82f6',
    bg: 'rgba(59,130,246,.12)',
    image: 'https://image-cdn-ak.spotifycdn.com/image/ab6772ab000015be97abe96098be58f61d240bd6',
    icon: '🔮',
    bio: '英國知名靈媒與心理測試師，準確預言多次重大政治事件，著有多本預言著作',
    tags: ['英國靈媒', '心靈感應', '政治預言'],
  },
  '麥克蒙尼格': {
    en: 'Joe McMoneagle',
    label: '麥克蒙尼格',
    color: '#10b981',
    bg: 'rgba(16,185,129,.12)',
    image: 'https://image-cdn-fa.spotifycdn.com/image/ab6772ab000015be5f38020222b3acd834a09208',
    icon: '👁',
    bio: 'CIA 星門計畫 #001 遙視員，前美軍情報官，曾精確畫出蘇聯潛艇結構並定位被綁架的將軍',
    tags: ['CIA', '遙視', '軍事情報'],
  },
  '摩普萊': {
    en: 'Morphee',
    label: '摩普萊',
    color: '#ef4444',
    bg: 'rgba(239,68,68,.12)',
    image: 'https://image-cdn-ak.spotifycdn.com/image/ab6772ab000015be8efbde8873f59858696cde97',
    icon: '⚡',
    bio: '神秘靈性感應者，以通靈方式預見全球軍事衝突與地球能量轉換',
    tags: ['靈性感應', '末日', '神秘學'],
  },
  '波蘭預言家': {
    en: 'Polish Prophet',
    label: '波蘭預言家',
    color: '#8b5cf6',
    bg: 'rgba(139,92,246,.12)',
    image: 'https://image-cdn-ak.spotifycdn.com/image/ab6772ab000015be995702a054887c23c9fe1eb1',
    icon: '⭐',
    bio: '東歐神秘預言家，預見美軍撤離波蘭、西方體制崩潰及黃金時代到來',
    tags: ['歐洲', '政治預言', '黃金時代'],
  },
  '英國神算': {
    en: 'British Psychic',
    label: '英國神算',
    color: '#06b6d4',
    bg: 'rgba(6,182,212,.12)',
    image: 'https://image-cdn-ak.spotifycdn.com/image/ab6772ab000015be00c37464272b2a19f45af82b',
    icon: '🌊',
    bio: '英國著名神秘學者，預見全球秩序大洗牌、能源革命與西方民主體制的根本轉變',
    tags: ['英國', '神秘學', '能源革命'],
  },
  '巴夏': {
    en: 'Bashar (Darryl Anka)',
    label: '巴夏',
    color: '#818cf8',
    bg: 'rgba(129,140,248,.12)',
    image: '/prophets/darryl-anka.jpg',
    icon: '🌌',
    bio: '由達雷爾·安卡（Darryl Anka）傳訊的外星意識實體，來自未來的伊沙薩尼文明，傳達宇宙法則與高頻振動訊息已逾40年',
    tags: ['外星通靈', '高維意識', '宇宙法則'],
  },
  '薩洛梅': {
    en: 'Athos Salomé',
    label: '薩洛梅',
    color: '#14b8a6',
    bg: 'rgba(20,184,166,.12)',
    image: '/prophets/athos-salome.webp',
    icon: '🔯',
    bio: '巴西靈媒與靈數學家，被媒體稱為「活著的諾查丹瑪斯」，精確預言COVID-19大流行、女王駕崩與多起全球重大事件',
    tags: ['巴西靈媒', '靈數學', '活諾查丹瑪斯'],
  },
  'Troy Black': {
    en: 'Troy Black',
    label: 'Troy Black',
    color: '#f97316',
    bg: 'rgba(249,115,22,.12)',
    image: '/prophets/troy-black.webp',
    icon: '✝️',
    bio: '德州基督教預言家、暢銷書作者，曾上 Sid Roth「超自然之事」節目，以異象與感動分享末世信息',
    tags: ['基督教預言', '美國', '末世'],
  },
  '鄭博見': {
    en: 'Dato Anthony Cheng',
    label: '鄭博見',
    color: '#d97706',
    bg: 'rgba(217,119,6,.12)',
    image: '/prophets/zheng-bojian.jpg',
    icon: '☯️',
    bio: '馬來西亞拿督，易經預測教師，聲稱於2019年預言COVID-19及全球停擺，被國際媒體譽為現代史上預測最準確的人之一',
    tags: ['易經', '東南亞', '財富預言'],
  },
  'KFK': {
    en: 'KFK (Future Person 2060)',
    label: 'KFK',
    color: '#06b6d4',
    bg: 'rgba(6,182,212,.12)',
    image: '/prophets/kfk.webp',
    icon: '⏰',
    bio: '2019年出現於豆瓣的神秘網路人物，自稱來自2060年的上海，在短時間內回答281個問題，多項預言已應驗',
    tags: ['未來人', '時間旅行', '中國互聯網'],
  },
  'David the Medium': {
    en: 'David the Medium',
    label: 'David the Medium',
    color: '#5b21b6',
    bg: 'rgba(91,33,182,.12)',
    image: '/prophets/david-the-medium.webp',
    icon: '🔮',
    bio: '澳洲頂級靈媒，前政府反恐刑事起訴官，以法律人嚴謹思維結合靈性感知，曾精準預言新冠疫情墨爾本封城及川普遇刺事件',
    tags: ['靈媒', '澳洲', '先知'],
  },
  'Tatsuki Ryo': {
    en: 'Tatsuki Ryo',
    label: 'Tatsuki Ryo',
    color: '#ec4899',
    bg: 'rgba(236,72,153,.12)',
    image: '/prophets/tatsuki-ryo.jpg',
    icon: '🌸',
    bio: '日本漫畫家，1999年出版《我所看見的未來》，以夢境日記形式預言1995年神戶大地震、2011年311海嘯等多起災難',
    tags: ['日本', '漫畫', '夢境預言'],
  },
  'Paul Begley': {
    en: 'Paul Begley',
    label: 'Paul Begley',
    color: '#dc2626',
    bg: 'rgba(220,38,38,.12)',
    image: '/prophets/paul-begley.webp',
    icon: '🔥',
    bio: '美國印第安納州福音浸信教會牧師，以《The Coming Apocalypse》節目聞名，YouTube累計逾2.4億次觀看，深入解讀聖經末日預言',
    tags: ['基督教預言', '美國牧師', '啟示錄'],
  },
  '阿南德': {
    en: 'Abhigya Anand',
    label: '阿南德',
    color: '#f59e0b',
    bg: 'rgba(245,158,11,.12)',
    image: '/prophets/abhigya-anand.jpg',
    icon: '🪐',
    bio: '印度吠陀占星師，11歲起研習占星，2019年預言COVID-19疫情大流行，獲全球兒童天才獎占星類冠軍，創辦 Praajna Jyotisha 研究所',
    tags: ['印度占星', '吠陀占星', '神童'],
  },
  '權朗': {
    en: 'Quan Lang',
    label: '權朗',
    color: '#9333ea',
    bg: 'rgba(147,51,234,.12)',
    image: '/prophets/quan-lang.jpg',
    icon: '☸️',
    bio: '香港玄學家，自稱茅山祖師後人、七仙女轉世，以通靈方式預言各國地震、瘟疫及政治動盪，聲稱137個神準預言全成真',
    tags: ['香港玄學', '茅山術', '通靈'],
  },
  '朱迪海文利': {
    en: 'Judy Hevenly',
    label: '朱迪海文利',
    color: '#e11d48',
    bg: 'rgba(225,29,72,.12)',
    image: '/prophets/judy-hevenly.jpg',
    icon: '⭐',
    bio: '洛杉磯著名靈媒與占星師，客戶包括皇室成員、前總統及好萊塢明星，年度預測準確率約90%，著有多本占星著作',
    tags: ['美國靈媒', '占星師', '名人靈媒'],
  },
  '國分玲': {
    en: 'Kokubun Rei',
    label: '國分玲',
    color: '#a855f7',
    bg: 'rgba(168,85,247,.12)',
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=160&h=160&fit=crop',
    icon: '🌙',
    bio: '日本神秘預言家，以靈視與通靈方式預言日本及全球重大事件',
    tags: ['日本預言', '靈視', '通靈'],
  },
  'Omnec Onec': {
    en: 'Omnec Onec',
    label: 'Omnec Onec',
    color: '#7c3aed',
    bg: 'rgba(124,58,237,.12)',
    image: '/prophets/omnec-onec.jpg',
    icon: '🛸',
    bio: '自稱來自金星的外星人大使，於1955年降臨地球，傳遞星際和平訊息與揚升教導',
    tags: ['外星接觸', '金星', '揚升'],
  },
  'Martin Armstrong': {
    en: 'Martin Armstrong',
    label: 'Martin Armstrong',
    color: '#059669',
    bg: 'rgba(5,150,105,.12)',
    image: '/prophets/martin-armstrong.png',
    icon: '📈',
    bio: '美國著名經濟預測師，開發 Socrates AI 週期模型，以精確預測金融危機、政治轉折聞名',
    tags: ['經濟預測', 'AI模型', '週期理論'],
  },
  'Jucelino': {
    en: 'Jucelino Nobrega da Luz',
    label: 'Jucelino',
    color: '#b45309',
    bg: 'rgba(180,83,9,.12)',
    image: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=160&h=160&fit=crop',
    icon: '💫',
    bio: '巴西預言家，自幼透過夢境預言未來，已向媒體預告多起重大災難與政治事件',
    tags: ['巴西', '夢境預言', '末世'],
  },
  'Jessica Adams': {
    en: 'Jessica Adams',
    label: 'Jessica Adams',
    color: '#be185d',
    bg: 'rgba(190,24,93,.12)',
    image: 'https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?w=160&h=160&fit=crop',
    icon: '♊',
    bio: '英國知名占星師，為《Vogue》《Cosmopolitan》等媒體撰寫星座專欄，以冥王星週期預測政治與社會變遷',
    tags: ['英國占星', '星座', '行星週期'],
  },
  'J.D. Farag': {
    en: 'J.D. Farag',
    label: 'J.D. Farag',
    color: '#1d4ed8',
    bg: 'rgba(29,78,216,.12)',
    image: '/prophets/jd-farag.webp',
    icon: '📖',
    bio: '夏威夷阿拉伯裔基督教牧師，以每週聖經預言更新聞名，深入分析末世徵兆與聖地政局',
    tags: ['基督教預言', '聖地', '末世徵兆'],
  },
  'Adam Archon': {
    en: 'Adam Archon',
    label: 'Adam Archon',
    color: '#7c3aed',
    bg: 'rgba(124,58,237,.12)',
    image: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=160&h=160&fit=crop',
    icon: '🔮',
    bio: '神秘學研究者，探索靈知主義與隱秘知識，分析地球隱藏勢力與人類覺醒進程',
    tags: ['靈知主義', '神秘學', '覺醒'],
  },
  '2062': {
    en: 'Future Person 2062',
    label: '2062',
    color: '#0891b2',
    bg: 'rgba(8,145,178,.12)',
    image: 'https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?w=160&h=160&fit=crop',
    icon: '⏳',
    bio: '自稱來自2062年的網路神秘人物，在匿名討論板留下對未來世界格局的多項預言',
    tags: ['未來人', '時間旅行', '網路傳說'],
  },
  '2075': {
    en: 'Future Person 2075',
    label: '2075',
    color: '#0e7490',
    bg: 'rgba(14,116,144,.12)',
    image: 'https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?w=160&h=160&fit=crop',
    icon: '⏳',
    bio: '自稱來自2075年的網路神秘人物，留下對人類科技與文明演變的多項預測',
    tags: ['未來人', '時間旅行', '網路傳說'],
  },
  '3906': {
    en: 'Future Person 3906',
    label: '3906',
    color: '#155e75',
    bg: 'rgba(21,94,117,.12)',
    image: 'https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?w=160&h=160&fit=crop',
    icon: '⏳',
    bio: '自稱來自遙遠未來3906年的神秘人物，帶來關於人類終極命運的驚人預言',
    tags: ['未來人', '時間旅行', '網路傳說'],
  },
  '3036': {
    en: 'Future Person 3036',
    label: '3036',
    color: '#164e63',
    bg: 'rgba(22,78,99,.12)',
    image: 'https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?w=160&h=160&fit=crop',
    icon: '⏳',
    bio: '自稱來自3036年的時間旅行者，描述未來人類的生活與地球的狀態',
    tags: ['未來人', '時間旅行', '網路傳說'],
  },
  'jjjkf.j': {
    en: 'jjjkf.j',
    label: 'jjjkf.j',
    color: '#0ea5e9',
    bg: 'rgba(14,165,233,.12)',
    image: 'https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?w=160&h=160&fit=crop',
    icon: '⏳',
    bio: '神秘網路預言人物，留下一系列關於未來的預測',
    tags: ['未來人', '網路傳說'],
  },
  '袁天罡與李淳風': {
    en: 'Yuan Tiangang & Li Chunfeng',
    label: '袁天罡與李淳風',
    color: '#92400e',
    bg: 'rgba(146,64,14,.12)',
    image: 'https://images.unsplash.com/photo-1581299894007-aaa50297cf16?w=160&h=160&fit=crop',
    icon: '📜',
    bio: '唐代兩位傳奇預言家，合著《推背圖》，以六十象預測中國歷代更迭，被譽為千年奇書',
    tags: ['推背圖', '唐代', '千年預言'],
  },
  '倪海廈': {
    en: 'Ni Haixia',
    label: '倪海廈',
    color: '#065f46',
    bg: 'rgba(6,95,70,.12)',
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=160&h=160&fit=crop',
    icon: '🀄',
    bio: '台美知名中醫師與命理學家，以八字、紫微斗數深入分析個人命運與國家大勢，著作影響深遠',
    tags: ['中醫', '八字', '紫微斗數'],
  },
  'Sadhguru': {
    en: 'Sadhguru',
    label: 'Sadhguru',
    color: '#92400e',
    bg: 'rgba(146,64,14,.12)',
    image: '/prophets/sadhguru.jpg',
    icon: '🕉️',
    bio: '印度靈性導師與瑜伽師，伊薩基金會創辦人，對人類意識進化、環境危機與文明走向有深刻洞見',
    tags: ['印度靈性', '瑜伽', '意識覺醒'],
  },
  'Clif High': {
    en: 'Clif High',
    label: 'Clif High',
    color: '#1e40af',
    bg: 'rgba(30,64,175,.12)',
    image: '/prophets/clif-high.jpg',
    icon: '💻',
    bio: '美國未來學家，開發網路爬蟲「預測語言模型」分析大數據，以集體潛意識方式預測未來趨勢',
    tags: ['大數據預測', '語言模型', '集體意識'],
  },
  'Lee Carroll': {
    en: 'Lee Carroll',
    label: 'Lee Carroll',
    color: '#1d4ed8',
    bg: 'rgba(29,78,216,.12)',
    image: '/prophets/lee-carroll.jpg',
    icon: '✨',
    bio: '美國靈性作家，自1989年起傳訊「克里昂」高維存在，著有逾17本克里昂系列書籍，傳遞新時代揚升訊息',
    tags: ['克里昂', '通靈', '揚升'],
  },
  'Jonathan Cahn': {
    en: 'Jonathan Cahn',
    label: 'Jonathan Cahn',
    color: '#1e3a8a',
    bg: 'rgba(30,58,138,.12)',
    image: '/prophets/jonathan-cahn.jpg',
    icon: '✡️',
    bio: '美國彌賽亞派猶太拉比，《秘密》系列暢銷書作者，以《撒米塔》《哈尔巴金》等古代預言解讀現代事件',
    tags: ['猶太預言', '聖經密碼', '末世'],
  },
  'Ray Kurzweil': {
    en: 'Ray Kurzweil',
    label: 'Ray Kurzweil',
    color: '#047857',
    bg: 'rgba(4,120,87,.12)',
    image: '/prophets/ray-kurzweil.jpg',
    icon: '🤖',
    bio: 'Google 工程總監、未來學家，以「奇點理論」預測2045年AI超越人類，過去90%以上預測已應驗',
    tags: ['科技奇點', 'AI', '未來學'],
  },
  'Joseph Tittel': {
    en: 'Joseph Tittel',
    label: 'Joseph Tittel',
    color: '#7c3aed',
    bg: 'rgba(124,58,237,.12)',
    image: '/prophets/joseph-tittel.jpg',
    icon: '🔮',
    bio: '美國靈媒，每年發布年度預言，涵蓋政治、災難與個人運勢，擁有龐大追隨者社群',
    tags: ['美國靈媒', '年度預言', '靈視'],
  },
  'Jackowski': {
    en: 'Krzysztof Jackowski',
    label: 'Jackowski',
    color: '#6b21a8',
    bg: 'rgba(107,33,168,.12)',
    image: '/prophets/jackowski.jpg',
    icon: '🌍',
    bio: '波蘭知名預言家 Krzysztof Jackowski，以遠距透視（clairvoyance）協助警方破案，並對全球政治動盪提出警告',
    tags: ['波蘭', '遠距透視', '政治預言'],
  },
  'Jeane Dixon': {
    en: 'Jeane Dixon',
    label: 'Jeane Dixon',
    color: '#9d174d',
    bg: 'rgba(157,23,77,.12)',
    image: '/prophets/jeane-dixon.jpg',
    icon: '🔮',
    bio: '美國20世紀最著名靈媒，預言甘迺迪總統遇刺，曾擔任多位美國總統的非官方顧問',
    tags: ['美國靈媒', '政治預言', '20世紀'],
  },
  'Susan Miller': {
    en: 'Susan Miller',
    label: 'Susan Miller',
    color: '#831843',
    bg: 'rgba(131,24,67,.12)',
    image: '/prophets/susan-miller.jpg',
    icon: '♊',
    bio: '美國知名占星師，創辦 AstrologyZone 網站，每月撰寫詳盡星座運勢預測，全球訪客逾1,200萬',
    tags: ['美國占星', '月度預測', 'AstrologyZone'],
  },
  'amanda-grace': {
    en: 'Amanda Grace',
    label: 'Amanda Grace',
    color: '#be185d',
    bg: 'rgba(190,24,93,.12)',
    image: '/prophets/amanda-grace.jpg',
    icon: '🕊️',
    bio: '美國基督教預言家，Ark of Grace Ministry 創辦人，以夢境異象及直接神諭分享末世警告與復興信息',
    tags: ['基督教預言', '美國', '神諭'],
  },
  'Jennifer LeClaire': {
    en: 'Jennifer LeClaire',
    label: 'Jennifer LeClaire',
    color: '#7c3aed',
    bg: 'rgba(124,58,237,.12)',
    image: '/prophets/jennifer-leclaire.webp',
    icon: '🔮',
    bio: '美國先知、作家及 Awakening House of Prayer 創辦人，以夢境異象分享末世警告，涵蓋美國政局、經濟泡沫與全球地緣政治預言',
    tags: ['基督教預言', '先知', '美國'],
  },
  'Joni Patry': {
    en: 'Joni Patry',
    label: 'Joni Patry',
    color: '#9a3412',
    bg: 'rgba(154,52,18,.12)',
    image: '/prophets/joni-patry.png',
    icon: '🪐',
    bio: '美國吠陀占星師，Galactic Center 創辦人，以行星週期精準預測全球政治與金融趨勢',
    tags: ['吠陀占星', '行星週期', '全球預測'],
  },
  'William Taylor': {
    en: 'William Taylor',
    label: 'William Taylor',
    color: '#1e40af',
    bg: 'rgba(30,64,175,.12)',
    image: 'https://images.unsplash.com/photo-1438232992991-80022131f5a1?w=160&h=160&fit=crop',
    icon: '✝️',
    bio: '基督教先知，以異象與預言分享對美國及全球末世格局的洞見',
    tags: ['基督教預言', '先知', '末世'],
  },
  'Julie Poole': {
    en: 'Julie Poole',
    label: 'Julie Poole',
    color: '#6d28d9',
    bg: 'rgba(109,40,217,.12)',
    image: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=160&h=160&fit=crop',
    icon: '💜',
    bio: '英國靈性教練與通靈師，透過高層次導師訊息分享個人療癒與地球轉化預言',
    tags: ['英國靈性', '通靈', '療癒'],
  },
  'Nikki Dutta': {
    en: 'Nikki (Nikki Dutta)',
    label: 'Nikki Dutta',
    color: '#b91c1c',
    bg: 'rgba(185,28,28,.12)',
    image: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=160&h=160&fit=crop',
    icon: '🔮',
    bio: '加拿大通靈師，年度預測涵蓋政治、名人與全球事件，以預言準確度廣受關注',
    tags: ['加拿大靈媒', '年度預測', '政治預言'],
  },
  'Michael Newton': {
    en: 'Michael Newton',
    label: 'Michael Newton',
    color: '#0f766e',
    bg: 'rgba(15,118,110,.12)',
    image: 'https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?w=160&h=160&fit=crop',
    icon: '🌿',
    bio: '美國催眠治療師，以前世回溯研究聞名，著有《靈魂旅程》等書，揭示靈魂在兩世之間的生命藍圖',
    tags: ['前世回溯', '催眠', '靈魂研究'],
  },
  'Clifford Mahooty': {
    en: 'Clifford Mahooty',
    label: 'Clifford Mahooty',
    color: '#78350f',
    bg: 'rgba(120,53,15,.12)',
    image: 'https://images.unsplash.com/photo-1506318137071-a8e063b4bec0?w=160&h=160&fit=crop',
    icon: '🦅',
    bio: '美國祖尼族長老，傳承古老星際知識，以原住民傳說與天空守護者（Star Beings）教義詮釋地球變遷',
    tags: ['原住民預言', '星際知識', '祖尼族'],
  },
  'Ian Bremmer': {
    en: 'Ian Bremmer',
    label: 'Ian Bremmer',
    color: '#1e3a8a',
    bg: 'rgba(30,58,138,.12)',
    image: '/prophets/ian-bremmer.jpg',
    icon: '🌍',
    bio: '美國政治學家，歐亞集團創辦人，以地緣政治風險分析著稱，年度「十大風險」預測廣受國際媒體引用',
    tags: ['地緣政治', '風險分析', '國際關係'],
  },
  'Jemima Packington': {
    en: 'Jemima Packington',
    label: 'Jemima Packington',
    color: '#166534',
    bg: 'rgba(22,101,52,.12)',
    image: 'https://images.unsplash.com/photo-1490750967868-88df5691cc81?w=160&h=160&fit=crop',
    icon: '🌿',
    bio: '英國唯一以「蘆筍占卜」預言未來的神算，每年元旦拋撒蘆筍枝，解讀擺放形態預測當年大事',
    tags: ['英國', '蘆筍占卜', '年度預言'],
  },
  'Laarkmaa': {
    en: 'Laarkmaa',
    label: 'Laarkmaa',
    color: '#5b21b6',
    bg: 'rgba(91,33,182,.12)',
    image: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=160&h=160&fit=crop',
    icon: '🌌',
    bio: '自稱來自昴宿星的星際存在，透過 Cullen & Pia Smith 傳訊，傳達宇宙演化與人類意識提升的訊息',
    tags: ['昴宿星', '通靈', '星際存在'],
  },
  'Love Me Do': {
    en: 'Love Me Do',
    label: 'Love Me Do',
    color: '#be123c',
    bg: 'rgba(190,18,60,.12)',
    image: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=160&h=160&fit=crop',
    icon: '💖',
    bio: '台灣知名靈媒，以愛與光傳遞靈訊，對台灣社會、感情與個人命運提供預測指引',
    tags: ['台灣靈媒', '靈訊', '感情預測'],
  },
  'Anne Tucker': {
    en: 'Anne Tucker',
    label: 'Anne Tucker',
    color: '#0369a1',
    bg: 'rgba(3,105,161,.12)',
    image: '/prophets/anne-tucker.webp',
    icon: '🌟',
    bio: '靈媒與預言家，透過靈視與感知分享對個人與全球事件的洞見',
    tags: ['靈媒', '靈視', '預言'],
  },
  'ADI': {
    en: 'ADI',
    label: 'ADI',
    color: '#6d28d9',
    bg: 'rgba(109,40,217,.12)',
    image: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=160&h=160&fit=crop',
    icon: '🌌',
    bio: '神秘靈性實體或頻道，傳遞關於地球演化與人類意識轉化的高維訊息',
    tags: ['高維意識', '靈性', '通靈'],
  },
  '阿洛伊斯': {
    en: 'Alois (Irlmaier)',
    label: '阿洛伊斯',
    color: '#7f1d1d',
    bg: 'rgba(127,29,29,.12)',
    image: 'https://images.unsplash.com/photo-1581299894007-aaa50297cf16?w=160&h=160&fit=crop',
    icon: '⚔️',
    bio: '20世紀德國巴伐利亞著名預言家 Alois Irlmaier，以靈視精確預言二戰結果，並留下對第三次世界大戰的詳細描述',
    tags: ['德國預言', '二戰', '第三次世界大戰'],
  },
  '蔡上機': {
    en: 'Cai Shangji',
    label: '蔡上機',
    color: '#78350f',
    bg: 'rgba(120,53,15,.12)',
    image: 'https://images.unsplash.com/photo-1581299894007-aaa50297cf16?w=160&h=160&fit=crop',
    icon: '📜',
    bio: '台灣命理預言家，融合易經、命理與天象解讀，對台灣政局與兩岸關係提出獨到預言',
    tags: ['台灣', '命理', '政治預言'],
  },
  '杜金龍': {
    en: 'Du Jinlong',
    label: '杜金龍',
    color: '#374151',
    bg: 'rgba(55,65,81,.12)',
    image: 'https://images.unsplash.com/photo-1581299894007-aaa50297cf16?w=160&h=160&fit=crop',
    icon: '🐉',
    bio: '台灣風水命理師，以八字、紫微斗數分析個人命運與國家氣運，對台灣社會現象有深入解讀',
    tags: ['台灣', '風水', '八字'],
  },
  '張盛舒': {
    en: 'Zhang Shengshu',
    label: '張盛舒',
    color: '#1f2937',
    bg: 'rgba(31,41,55,.12)',
    image: 'https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?w=160&h=160&fit=crop',
    icon: '⭐',
    bio: '台灣知名占星師，創辦 iStars 星座網站，以西洋占星解讀個人命運與年度趨勢',
    tags: ['台灣', '占星師', '星座'],
  },
  '若海': {
    en: 'Ruohai',
    label: '若海',
    color: '#0f4c81',
    bg: 'rgba(15,76,129,.12)',
    image: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=160&h=160&fit=crop',
    icon: '🌊',
    bio: '中文網路神秘預言人物，以天道視角分析全球局勢走向',
    tags: ['網路預言', '天道', '全球局勢'],
  },
  '小孟老師': {
    en: 'Master Xiaomeng',
    label: '小孟老師',
    color: '#0ea5e9',
    bg: 'rgba(14,165,233,.12)',
    image: '/prophets/xiaomeng.webp',
    icon: '🃏',
    bio: '清水孟國際塔羅小孟老師，以星象、塔羅牌及大數據解讀財經趨勢與國運走向',
    tags: ['塔羅', '財經命理', '台灣'],
  },
  '廖美然': {
    en: 'Liao Meiran',
    label: '廖美然',
    color: '#7c3aed',
    bg: 'rgba(124,58,237,.12)',
    image: '/prophets/liao-meiran.webp',
    icon: '🔮',
    bio: '台灣靈媒，被譽為「台灣觀世音」，以通靈感應預言政治、自然災害及全球局勢',
    tags: ['靈媒', '通靈', '台灣'],
  },
};

export const DEFAULT_PROPHET: ProphetConfig = {
  en: 'Future Predictor',
  label: '未來人預言家',
  color: '#7c3aed',
  bg: 'rgba(124,58,237,.12)',
  image: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=160&h=160&fit=crop',
  icon: '🐻',
  bio: '兩隻熊頻道精心整理的末日預言與靈性啟示，帶你理性面對感性預言',
  tags: ['預言', '末日'],
};

export function getProphetConfig(name: string): ProphetConfig {
  return PROPHETS[name] ?? DEFAULT_PROPHET;
}

export function detectProphet(title: string): string {
  if (/比格斯|biggs/i.test(title)) return '比格斯';
  if (/帕克|parker/i.test(title)) return '帕克';
  if (/麥克蒙尼格|mcmoneagle|遙視員/i.test(title)) return '麥克蒙尼格';
  if (/摩普萊/i.test(title)) return '摩普萊';
  if (/波蘭預言家/i.test(title)) return '波蘭預言家';
  if (/英國神算/i.test(title)) return '英國神算';
  if (/巴夏|bashar|darryl.?anka/i.test(title)) return '巴夏';
  if (/薩洛梅|salomé|athos.?salom/i.test(title)) return '薩洛梅';
  if (/troy.?black/i.test(title)) return 'Troy Black';
  if (/鄭博見|zheng.?bojian|dato.?anthony/i.test(title)) return '鄭博見';
  if (/KFK|kfk/i.test(title)) return 'KFK';
  if (/tatsuki|辰巳りよ/i.test(title)) return 'Tatsuki Ryo';
  if (/paul.?begley/i.test(title)) return 'Paul Begley';
  if (/abhigya|阿南德/i.test(title)) return '阿南德';
  if (/權朗|quan.?lang/i.test(title)) return '權朗';
  if (/朱迪|judy.?hev/i.test(title)) return '朱迪海文利';
  if (/國分玲|kokubun/i.test(title)) return '國分玲';
  if (/omnec.?onec/i.test(title)) return 'Omnec Onec';
  if (/martin.?armstrong/i.test(title)) return 'Martin Armstrong';
  if (/jucelino/i.test(title)) return 'Jucelino';
  if (/jessica.?adams/i.test(title)) return 'Jessica Adams';
  if (/j\.?d\.?.?farag/i.test(title)) return 'J.D. Farag';
  if (/adam.?archon/i.test(title)) return 'Adam Archon';
  if (/袁天罡|李淳風|推背圖/i.test(title)) return '袁天罡與李淳風';
  if (/倪海廈/i.test(title)) return '倪海廈';
  if (/sadhguru/i.test(title)) return 'Sadhguru';
  if (/clif.?high/i.test(title)) return 'Clif High';
  if (/lee.?carroll|克里昂/i.test(title)) return 'Lee Carroll';
  if (/jonathan.?cahn/i.test(title)) return 'Jonathan Cahn';
  if (/ray.?kurzweil/i.test(title)) return 'Ray Kurzweil';
  if (/joseph.?tittel/i.test(title)) return 'Joseph Tittel';
  if (/jackowski/i.test(title)) return 'Jackowski';
  if (/jeane.?dixon/i.test(title)) return 'Jeane Dixon';
  if (/susan.?miller/i.test(title)) return 'Susan Miller';
  if (/amanda.?grace/i.test(title)) return 'amanda-grace';
  if (/jennifer.?leclaire|leclaire/i.test(title)) return 'Jennifer LeClaire';
  if (/david.the.medium|david.*medium|靈媒.*大衛|大衛.*靈媒/i.test(title)) return 'David the Medium';
  if (/小孟/i.test(title)) return '小孟老師';
  if (/廖美然|觀世音.*廖/i.test(title)) return '廖美然';
  if (/joni.?patry/i.test(title)) return 'Joni Patry';
  if (/william.?taylor/i.test(title)) return 'William Taylor';
  if (/阿洛伊斯|irlmaier/i.test(title)) return '阿洛伊斯';
  if (/蔡上機/i.test(title)) return '蔡上機';
  if (/杜金龍/i.test(title)) return '杜金龍';
  if (/張盛舒/i.test(title)) return '張盛舒';
  if (/ian.?bremmer/i.test(title)) return 'Ian Bremmer';
  if (/clifford.?mahooty/i.test(title)) return 'Clifford Mahooty';
  return '';
}
