// Cloudflare Pages build orchestrator.
// - Hides SSR-only dirs (api/, admin/, keystatic/) and interactive pages by renaming them with a `_` prefix
//   (Astro ignores files/dirs prefixed with `_` in src/pages).
// - Runs astro build with PUBLIC_DEPLOY_TARGET=cloudflare and no Vercel adapter.
// - Snapshots dynamic APIs (podcast-rss) as static files under dist/api/.
// - Writes dist/_redirects and dist/_headers.
// - Restores every rename on success, error, or signal — verifies git working tree is clean at start & end.

import { renameSync, existsSync, writeFileSync, mkdirSync } from 'node:fs';
import { execSync, spawnSync } from 'node:child_process';
import { resolve } from 'node:path';
import { writeRedirects, totalRedirectCount } from './gen-cf-redirects.mjs';
import { snapshotPodcast } from './snapshot-podcast.mjs';

const PAGES_DIR = resolve('src/pages');

// Directories to hide (rename to `_<name>_hidden`)
const HIDE_DIRS = ['api', 'admin', 'keystatic', 'tools'];
// Individual page files to hide (interactive/broken-without-API pages)
const HIDE_FILES = [
  'cruise.astro', 'hotels.astro', 'food.astro', 'omikuji.astro', 'oracle.astro', 'biggsgpt.astro',
  'member.astro', 'travel-news.astro', 'friends.astro', 'fortune.astro',
  'pick.astro', 'picks.astro', 'language.astro',
];

const renames = []; // [{from, to}]

function checkGitClean(label) {
  try {
    // Ignore untracked (??) — only fail on tracked-file modifications
    const out = execSync('git status --porcelain src/pages', { encoding: 'utf-8' })
      .split('\n').filter(l => l && !l.startsWith('??')).join('\n');
    if (out.trim()) {
      throw new Error(
        `[build-cf] git working tree in src/pages is not clean (${label}):\n${out}\n` +
        `Commit or stash changes before running build:cf.`
      );
    }
  } catch (e) {
    if (e.message.includes('not clean')) throw e;
    console.warn(`[build-cf] git status check skipped: ${e.message}`);
  }
}

function hide() {
  for (const dir of HIDE_DIRS) {
    const from = resolve(PAGES_DIR, dir);
    const to = resolve(PAGES_DIR, `_${dir}_hidden`);
    if (existsSync(from)) {
      renameSync(from, to);
      renames.push({ from, to });
    }
  }
  for (const file of HIDE_FILES) {
    const from = resolve(PAGES_DIR, file);
    const to = resolve(PAGES_DIR, `_${file}`);
    if (existsSync(from)) {
      renameSync(from, to);
      renames.push({ from, to });
    }
  }
  console.log(`[build-cf] hid ${renames.length} paths in src/pages`);
}

function restore() {
  // Reverse order so nested renames unwind correctly.
  while (renames.length) {
    const { from, to } = renames.pop();
    if (existsSync(to)) {
      try { renameSync(to, from); }
      catch (e) { console.error(`[build-cf] restore failed for ${to} -> ${from}: ${e.message}`); }
    }
  }
  console.log('[build-cf] restored all renames');
}

// Ensure restore even on ctrl+c / crash
let restored = false;
function safeRestore() {
  if (restored) return;
  restored = true;
  restore();
}
process.on('SIGINT', () => { safeRestore(); process.exit(130); });
process.on('SIGTERM', () => { safeRestore(); process.exit(143); });
process.on('uncaughtException', (e) => { console.error(e); safeRestore(); process.exit(1); });

async function main() {
  checkGitClean('before build');
  hide();
  try {
    const env = { ...process.env, PUBLIC_DEPLOY_TARGET: 'cloudflare' };
    const res = spawnSync('npx', ['astro', 'build'], { stdio: 'inherit', env });
    if (res.status !== 0) throw new Error(`astro build exited with ${res.status}`);

    // Snapshot podcast RSS (3 retries; throws on final failure)
    await snapshotPodcast('dist');

    // Redirects
    const lineCount = writeRedirects('dist');
    console.log(`[build-cf] wrote dist/_redirects (${lineCount} lines, ${totalRedirectCount()} rules)`);

    // Headers: force JSON content-type for snapshot API files (no extension)
    mkdirSync('dist', { recursive: true });
    writeFileSync(
      resolve('dist/_headers'),
      [
        '# Auto-generated by scripts/build-cf.mjs',
        '/api/*',
        '  Content-Type: application/json; charset=utf-8',
        '  Cache-Control: public, max-age=300',
        '',
      ].join('\n'),
      'utf-8'
    );
    console.log('[build-cf] wrote dist/_headers');
  } finally {
    safeRestore();
    checkGitClean('after build');
  }
  console.log('[build-cf] SUCCESS');
}

main().catch(e => {
  console.error(e);
  safeRestore();
  process.exit(1);
});
